from assistant.handlers.contact_handlers import (
    contact_add,
    contact_change,
    contact_delete,
    contact_search,
    contact_search_name,
    contact_phone_add,
    contact_phone_change,
    contact_phone_delete,
    contact_phone_search,
    contact_email_add,
    contact_email_change,
    contact_email_delete,
    contact_email_search,
    contact_birthday_set,
    contact_birthday_change,
    contact_birthday_delete,
    contact_birthday_search,
    contact_address_set,
    contact_address_change,
    contact_address_delete,
    contact_address_search,
)

from assistant.handlers.note_handlers import (
    note_add,
    note_change,
    note_delete,
    note_search,
    note_tag_add,
    note_tag_change,
    note_tag_delete,
    note_tag_search,
)

from assistant.handlers.help_handlers import (
    help_default,
    help_contact,
    help_contact_add,
    help_contact_change,
    help_contact_delete,
    help_contact_search,
    help_contact_phone,
    help_contact_phone_add,
    help_contact_phone_change,
    help_contact_phone_delete,
    help_contact_phone_search,
    help_contact_email,
    help_contact_email_add,
    help_contact_email_change,
    help_contact_email_delete,
    help_contact_email_search,
    help_contact_birthday,
    help_contact_birthday_set,
    help_contact_birthday_change,
    help_contact_birthday_delete,
    help_contact_birthday_search,
    help_contact_address,
    help_contact_address_set,
    help_contact_address_change,
    help_contact_address_delete,
    help_contact_address_search,
    help_note,
    help_note_add,
    help_note_change,
    help_note_delete,
    help_note_search,
    help_note_tag,
    help_note_tag_add,
    help_note_tag_change,
    help_note_tag_delete,
    help_note_tag_search,
)


COMMANDS = {
    "exit": "exit",
    "close": "exit",
    "hello": lambda *_: "How can I help you?",
    "all": contact_search,
    "contact": {
        "/": help_contact,
        "add": contact_add,
        "change": contact_change,
        "delete": contact_delete,
        "search": {
            "/": contact_search,
            "name": contact_search_name,
        },
        "phone": {
            "/": help_contact_phone,
            "add": contact_phone_add,
            "change": contact_phone_change,
            "delete": contact_phone_delete,
            "search": contact_phone_search,
        },
        "email": {
            "/": help_contact_email,
            "add": contact_email_add,
            "change": contact_email_change,
            "delete": contact_email_delete,
            "search": contact_email_search,
        },
        "birthday": {
            "/": help_contact_birthday,
            "set": contact_birthday_set,
            "change": contact_birthday_change,
            "delete": contact_birthday_delete,
            "search": contact_birthday_search,
        },
        "address": {
            "/": help_contact_address,
            "set": contact_address_set,
            "change": contact_address_change,
            "delete": contact_address_delete,
            "search": contact_address_search,
        },
    },
    "note": {
        "/": help_note,
        "add": note_add,
        "change": note_change,
        "delete": note_delete,
        "search": note_search,
        "tag": {
            "/": help_note_tag,
            "add": note_tag_add,
            "change": note_tag_change,
            "delete": note_tag_delete,
            "search": note_tag_search,
        },
    },
    "help": {
        "/": help_default,
        "contact": {
            "/": help_contact,
            "add": help_contact_add,
            "change": help_contact_change,
            "delete": help_contact_delete,
            "search": help_contact_search,
            "phone": {
                "/": help_contact_phone,
                "add": help_contact_phone_add,
                "change": help_contact_phone_change,
                "delete": help_contact_phone_delete,
                "search": help_contact_phone_search,
            },
            "email": {
                "/": help_contact_email,
                "add": help_contact_email_add,
                "change": help_contact_email_change,
                "delete": help_contact_email_delete,
                "search": help_contact_email_search,
            },
            "birthday": {
                "/": help_contact_birthday,
                "set": help_contact_birthday_set,
                "change": help_contact_birthday_change,
                "delete": help_contact_birthday_delete,
                "search": help_contact_birthday_search,
            },
            "address": {
                "/": help_contact_address,
                "set": help_contact_address_set,
                "change": help_contact_address_change,
                "delete": help_contact_address_delete,
                "search": help_contact_address_search,
            },
        },
        "note": {
            "/": help_note,
            "add": help_note_add,
            "change": help_note_change,
            "delete": help_note_delete,
            "search": help_note_search,
            "tag": {
                "/": help_note_tag,
                "add": help_note_tag_add,
                "change": help_note_tag_change,
                "delete": help_note_tag_delete,
                "search": help_note_tag_search,
            },
        },
    },
}
