from assistant.handlers.contact_handlers import (
    contact_add,
    contact_change,
    contact_delete,
    contact_search,
    contact_phone_add,
    contact_phone_change,
    contact_phone_delete,
    contact_phone_search,
    contact_email_add,
    contact_email_change,
    contact_email_delete,
    contact_email_search,
    contact_birthday_set,
    contact_birthday_change,
    contact_birthday_delete,
    contact_birthday_search,
    contact_address_set,
    contact_address_change,
    contact_address_delete,
    contact_address_search,
)

from assistant.handlers.note_handlers import (
    note_add,
    note_change,
    note_delete,
    note_search,
    note_tag_add,
    note_tag_change,
    note_tag_delete,
    note_tag_search,
    note_tag_sort,
)

from assistant.handlers.help_handlers import (
    help_default,
    help_contact,
    help_contact_add,
    help_contact_change,
    help_contact_delete,
    help_contact_search,
    help_contact_phone,
    help_contact_phone_add,
    help_contact_phone_change,
    help_contact_phone_delete,
    help_contact_phone_search,
    help_contact_email,
    help_contact_email_add,
    help_contact_email_change,
    help_contact_email_delete,
    help_contact_email_search,
    help_contact_birthday,
    help_contact_birthday_set,
    help_contact_birthday_change,
    help_contact_birthday_delete,
    help_contact_birthday_search,
    help_contact_address,
    help_contact_address_set,
    help_contact_address_change,
    help_contact_address_delete,
    help_contact_address_search,
    help_note,
    help_note_add,
    help_note_change,
    help_note_delete,
    help_note_search,
    help_note_tag,
    help_note_tag_add,
    help_note_tag_change,
    help_note_tag_delete,
    help_note_tag_search,
    help_note_tag_sort,
)
from assistant.cli.exceptions import GoodByeException


def good_bye(*args):
    raise GoodByeException()


# Each command refers to a function or a tuple.
# For function it's simply called,
# Tuple has 2 items: function and minimum of params.
# If minimum of params has not reached, we call a corresponding help function
# If not - we call this function with all args we have received

commands_list = {
    "exit": good_bye,
    "close": good_bye,
    "hello": lambda *_: "How can I help you?",
    "all": (contact_search, 0),
    "contact": (help_contact, 0),
    "contact add": (contact_add, 1),
    "contact change": (contact_change, 2),
    "contact delete": (contact_delete, 1),
    "contact search": (
        contact_search,
        0,
    ),  # if 0 params - searches all, if 1 param - searches by this param
    "contact phone": (help_contact_phone, 0),
    "contact phone add": (contact_phone_add, 2),
    "contact phone change": (contact_phone_change, 3),
    "contact phone delete": (contact_phone_delete, 2),
    "contact phone search": (contact_phone_search, 1),  # for search we ignore the user
    "contact email": (help_contact_email, 0),
    "contact email add": (contact_email_add, 2),
    "contact email change": (contact_email_change, 3),
    "contact email delete": (contact_email_delete, 2),
    "contact email search": (contact_email_search, 1),
    "contact birthday": (help_contact_birthday, 0),
    "contact birthday set": (contact_birthday_set, 2),
    "contact birthday change": (contact_birthday_change, 2),
    "contact birthday delete": (contact_birthday_delete, 1),
    "contact birthday search": (contact_birthday_search, 1),
    "contact address": (help_contact_address, 0),
    "contact address set": (contact_address_set, 2),
    "contact address change": (contact_address_change, 2),
    "contact address delete": (contact_address_delete, 1),
    "contact address search": (contact_address_search, 1),
    "note": (help_note, 0),
    "note add": (note_add, 1),
    "note change": (note_change, 2),
    "note delete": (note_delete, 1),
    "note search": (note_search, 0),
    "note tag": (help_note_tag, 0),
    "note tag add": (note_tag_add, 2),
    "note tag change": (note_tag_change, 2),
    "note tag delete": (note_tag_delete, 1),
    "note tag search": (note_tag_search, 0),
    "note tag sort": (note_tag_sort, 0),
    "help": (help_default, 0),
    "help contact": (help_contact, 0),
    "help contact add": (help_contact_add, 0),
    "help contact change": (help_contact_change, 0),
    "help contact delete": (help_contact_delete, 0),
    "help contact search": (help_contact_search, 0),
    "help contact phone": (help_contact_phone, 0),
    "help contact phone add": (help_contact_phone_add, 0),
    "help contact phone change": (help_contact_phone_change, 0),
    "help contact phone delete": (help_contact_phone_delete, 0),
    "help contact phone search": (help_contact_phone_search, 0),
    "help contact email": (help_contact_email, 0),
    "help contact email add": (help_contact_email_add, 0),
    "help contact email change": (help_contact_email_change, 0),
    "help contact email delete": (help_contact_email_delete, 0),
    "help contact email search": (help_contact_email_search, 0),
    "help contact birthday": (help_contact_birthday, 0),
    "help contact birthday set": (help_contact_birthday_set, 0),
    "help contact birthday change": (help_contact_birthday_change, 0),
    "help contact birthday delete": (help_contact_birthday_delete, 0),
    "help contact birthday search": (help_contact_birthday_search, 0),
    "help contact address": (help_contact_address, 0),
    "help contact address set": (help_contact_address_set, 0),
    "help contact address change": (help_contact_address_change, 0),
    "help contact address delete": (help_contact_address_delete, 0),
    "help contact address search": (help_contact_address_search, 0),
    "help note": (help_note, 0),
    "help note add": (help_note_add, 0),
    "help note change": (help_note_change, 0),
    "help note delete": (help_note_delete, 0),
    "help note search": (help_note_search, 0),
    "help note tag": (help_note_tag, 0),
    "help note tag add": (help_note_tag_add, 0),
    "help note tag change": (help_note_tag_change, 0),
    "help note tag delete": (help_note_tag_delete, 0),
    "help note tag search": (help_note_tag_search, 0),
    "help note tag sort": (help_note_tag_sort, 0),
}
